# Generated by Django 4.1.7 on 2023-03-03 18:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Calculations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pension_contribution",
                    models.FloatField(default=0.0, verbose_name="Pension Contribution"),
                ),
                (
                    "disability_contribution",
                    models.FloatField(
                        default=0.0, verbose_name="Disability Contribution"
                    ),
                ),
                (
                    "sickness_contribution",
                    models.FloatField(
                        default=0.0, verbose_name="Sickness Contribution"
                    ),
                ),
                (
                    "health_care_contribution",
                    models.FloatField(
                        default=0.0, verbose_name="Health Care Contribution"
                    ),
                ),
                (
                    "income",
                    models.FloatField(
                        default=0.0,
                        help_text="Dopóki twoje burtto zarobek nie przekracza kosztów przychodu wynosi 0",
                        verbose_name="Income",
                    ),
                ),
                (
                    "income_tax",
                    models.FloatField(
                        default=0.0,
                        help_text="Dopóki twoje burtto zarobek nie przekracza kosztów przychodu wynosi 0",
                        verbose_name="Income tax",
                    ),
                ),
                (
                    "netto_salary",
                    models.FloatField(default=0, verbose_name="Netto salary"),
                ),
            ],
            options={
                "verbose_name": "calculations",
                "verbose_name_plural": "2. Financial calculations",
            },
        ),
        migrations.CreateModel(
            name="Constants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(auto_now=True, verbose_name="Constant at date"),
                ),
                ("PIT", models.FloatField(default=12, verbose_name="Constant PIT tax")),
                (
                    "pension_contribution",
                    models.FloatField(
                        default=9.78, verbose_name="Pension Contribution"
                    ),
                ),
                (
                    "disability_contribution",
                    models.FloatField(
                        default=1.5, verbose_name="Disability Contribution"
                    ),
                ),
                (
                    "sickness_contribution",
                    models.FloatField(
                        default=2.45, verbose_name="Sickness Contribution"
                    ),
                ),
                (
                    "health_care_contribution",
                    models.FloatField(
                        default=9, verbose_name="Health Care Contribution"
                    ),
                ),
            ],
            options={
                "verbose_name": "constants",
                "verbose_name_plural": "3. Constants for calculations",
            },
        ),
        migrations.CreateModel(
            name="Settlements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "calculations",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="earnings.calculations",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "settlements",
                "verbose_name_plural": "1. Settlements",
            },
        ),
        migrations.CreateModel(
            name="JobHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "hours",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=0,
                                message="Working hours cannot be less than 0",
                            )
                        ],
                    ),
                ),
                (
                    "extra_hours",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=0,
                                message="Working hours cannot be less than 0",
                            )
                        ],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "job hours",
                "verbose_name_plural": "4. Your job hours",
            },
        ),
        migrations.AddField(
            model_name="calculations",
            name="constants",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="earnings.constants"
            ),
        ),
        migrations.AddField(
            model_name="calculations",
            name="hours",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="earnings.jobhours"
            ),
        ),
        migrations.AddField(
            model_name="calculations",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
