# Generated by Django 4.1.6 on 2023-02-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("earnings", "0002_alter_calculations_user_alter_constants_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculations",
            name="disability_contribution",
            field=models.FloatField(
                default=0.0, verbose_name="Disability Contribution"
            ),
        ),
        migrations.AlterField(
            model_name="calculations",
            name="netto_salary",
            field=models.FloatField(default=0, verbose_name="Netto salary"),
        ),
    ]
