# Generated by Django 4.1.5 on 2023-01-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("earnings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="earnings",
            name="PIT",
            field=models.DecimalField(
                decimal_places=2, default=12, max_digits=5, verbose_name="PIT tax"
            ),
        ),
    ]
