# Generated by Django 4.1.5 on 2023-01-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("earnings", "0003_earnings_pit"),
    ]

    operations = [
        migrations.AddField(
            model_name="earnings",
            name="constant_disability_contribution",
            field=models.DecimalField(
                decimal_places=2,
                default=1.5,
                max_digits=5,
                verbose_name="Disability Contribution",
            ),
        ),
        migrations.AddField(
            model_name="earnings",
            name="constant_health_care_contribution",
            field=models.DecimalField(
                decimal_places=2,
                default=9,
                max_digits=5,
                verbose_name="Health Care Contribution",
            ),
        ),
        migrations.AddField(
            model_name="earnings",
            name="constant_pension_contribution",
            field=models.DecimalField(
                decimal_places=2,
                default=9.78,
                max_digits=5,
                verbose_name="Pension Contribution",
            ),
        ),
        migrations.AddField(
            model_name="earnings",
            name="constant_sickness_contribution",
            field=models.DecimalField(
                decimal_places=2,
                default=2.45,
                max_digits=5,
                verbose_name="Sickness Contribution",
            ),
        ),
    ]
