# Generated by Django 4.1.5 on 2023-02-01 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("earnings", "0013_alter_jobhours_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobhours",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
