# Generated by Django 4.1.5 on 2023-02-01 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("earnings", "0017_remove_jobhours__hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobhours",
            name="end_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="jobhours",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
