# Generated by Django 4.1.5 on 2023-02-01 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("earnings", "0018_alter_jobhours_end_date_alter_jobhours_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobhours",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 2, 18, 34, 21, 792740, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
