# Generated by Django 4.1.6 on 2023-02-07 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("earnings", "0020_alter_jobhours_end_date_alter_jobhours_start_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calculations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pension_contribution",
                    models.FloatField(
                        default=0, verbose_name="Calculated Pension Contribution"
                    ),
                ),
                (
                    "disability_contribution",
                    models.FloatField(
                        default=0, verbose_name="Calculated  Disability Contribution"
                    ),
                ),
                (
                    "sickness_contribution",
                    models.FloatField(
                        default=0, verbose_name="Calculated Sickness Contribution"
                    ),
                ),
                (
                    "health_care_contribution",
                    models.FloatField(
                        default=0, verbose_name="Calculated Health Care Contribution"
                    ),
                ),
                (
                    "income_tax",
                    models.FloatField(default=0, verbose_name="Calculated income tax"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Constants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pension_contribution",
                    models.FloatField(
                        default=9.78, verbose_name="Constant Pension Contribution"
                    ),
                ),
                (
                    "disability_contribution",
                    models.FloatField(
                        default=1.5, verbose_name="Constant  Disability Contribution"
                    ),
                ),
                (
                    "sickness_contribution",
                    models.FloatField(
                        default=2.45, verbose_name="Constant Sickness Contribution"
                    ),
                ),
                (
                    "health_care_contribution",
                    models.FloatField(
                        default=9, verbose_name="Constant Health Care Contribution"
                    ),
                ),
                ("PIT", models.FloatField(default=12, verbose_name="Constant PIT tax")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Salaries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("brutto_salary", models.FloatField()),
                ("netto_salary", models.FloatField()),
                (
                    "calculations",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="earnings.calculations",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Settlements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "calculations",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculationed",
                        to="earnings.calculations",
                    ),
                ),
                (
                    "constants",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="earnings.constants",
                    ),
                ),
                (
                    "salary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="converted",
                        to="earnings.salaries",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Earnings",
        ),
        migrations.AddField(
            model_name="calculations",
            name="constants",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="earnings.constants"
            ),
        ),
        migrations.AddField(
            model_name="calculations",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employer",
                to="earnings.settlements",
            ),
        ),
    ]
