# Generated by Django 4.1.6 on 2023-02-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("earnings", "0021_calculations_constants_salaries_settlements_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="calculations",
            old_name="user",
            new_name="settlement",
        ),
    ]
