# Generated by Django 4.1.6 on 2023-02-07 17:17

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("earnings", "0022_rename_user_calculations_settlement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobhours",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="jobhours",
            name="start_date",
        ),
        migrations.AddField(
            model_name="jobhours",
            name="end_job",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="jobhours",
            name="hours",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=0, message="Working hours cannot be less than 0"
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=24,
                        message="Working hours cannot be more than 24h. Day has 24h.",
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="jobhours",
            name="start_job",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="calculations",
            name="disability_contribution",
            field=models.FloatField(default=0, verbose_name=" Disability Contribution"),
        ),
        migrations.AlterField(
            model_name="calculations",
            name="health_care_contribution",
            field=models.FloatField(default=0, verbose_name="Health Care Contribution"),
        ),
        migrations.AlterField(
            model_name="calculations",
            name="income_tax",
            field=models.FloatField(default=0, verbose_name="Income tax"),
        ),
        migrations.AlterField(
            model_name="calculations",
            name="pension_contribution",
            field=models.FloatField(default=0, verbose_name="Pension Contribution"),
        ),
        migrations.AlterField(
            model_name="calculations",
            name="sickness_contribution",
            field=models.FloatField(default=0, verbose_name="Sickness Contribution"),
        ),
    ]
