# Generated by Django 4.1.6 on 2023-02-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "earnings",
            "0023_remove_jobhours_end_date_remove_jobhours_start_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calculations",
            name="settlement",
        ),
    ]
