# Generated by Django 4.1.6 on 2023-02-07 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("earnings", "0024_remove_calculations_settlement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settlements",
            name="user",
        ),
        migrations.AddField(
            model_name="calculations",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="salaries",
            name="brutto_salary",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="salaries",
            name="netto_salary",
            field=models.FloatField(default=0),
        ),
    ]
