# Generated by Django 4.1.6 on 2023-02-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("earnings", "0025_remove_settlements_user_calculations_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salaries",
            name="brutto_salary",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="salaries",
            name="netto_salary",
            field=models.FloatField(),
        ),
    ]
