# Generated by Django 4.1.6 on 2023-02-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("earnings", "0026_alter_salaries_brutto_salary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculations",
            name="brutto_salary",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="salaries",
            name="brutto_salary",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="salaries",
            name="netto_salary",
            field=models.FloatField(default=0),
        ),
    ]
