# Generated by Django 4.1.6 on 2023-02-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("earnings", "0027_calculations_brutto_salary_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calculations",
            name="brutto_salary",
        ),
        migrations.AddField(
            model_name="calculations",
            name="income",
            field=models.FloatField(default=0, verbose_name="Income"),
        ),
    ]
