# Generated by Django 4.1.6 on 2023-02-07 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("earnings", "0028_remove_calculations_brutto_salary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salaries",
            name="calculations",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="earnings.calculations"
            ),
        ),
    ]
