# Generated by Django 4.1.6 on 2023-02-07 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("earnings", "0029_alter_salaries_calculations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salaries",
            name="brutto_salary",
        ),
        migrations.RemoveField(
            model_name="salaries",
            name="netto_salary",
        ),
    ]
