# Generated by Django 4.1.6 on 2023-02-07 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("earnings", "0030_remove_salaries_brutto_salary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="constants",
            name="calculations",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calc",
                to="earnings.calculations",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="calculations",
            name="constants",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="constants",
                to="earnings.constants",
            ),
        ),
    ]
