# Generated by Django 4.1.6 on 2023-02-07 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("earnings", "0032_remove_constants_calculations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculations",
            name="constants",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="earnings.constants"
            ),
        ),
    ]
