# Generated by Django 4.1.6 on 2023-02-08 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("earnings", "0036_calculations_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobhours",
            name="extra_hours",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=0, message="Working hours cannot be less than 0"
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=24,
                        message="Working hours cannot be more than 24h. Day has 24h.",
                    ),
                ],
            ),
        ),
    ]
