# Generated by Django 4.1.6 on 2023-02-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("earnings", "0038_constants_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculations",
            name="netto_salary",
            field=models.FloatField(default=0),
        ),
    ]
