# Generated by Django 4.1.6 on 2023-02-09 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("earnings", "0039_calculations_netto_salary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calculations",
            name="netto_salary",
        ),
    ]
