# Generated by Django 4.1.6 on 2023-02-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("earnings", "0040_remove_calculations_netto_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculations",
            name="netto_salary",
            field=models.FloatField(default=0),
        ),
    ]
