# Generated by Django 4.1.6 on 2023-02-13 15:22

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("earnings", "0041_calculations_netto_salary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobhours",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="jobhours",
            name="extra_hours",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=0, message="Working hours cannot be less than 0"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="jobhours",
            name="hours",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=0, message="Working hours cannot be less than 0"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="jobhours",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
