# Generated by Django 4.1.6 on 2023-02-13 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "earnings",
            "0043_calculations_extra_hours_calculations_working_hours_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calculations",
            name="extra_hours",
        ),
        migrations.RemoveField(
            model_name="calculations",
            name="working_hours",
        ),
        migrations.AlterField(
            model_name="calculations",
            name="hours",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="earnings.jobhours"
            ),
        ),
    ]
