exclude: "^docs/|/migrations/"
default_stages: [commit, merge-commit, push]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        files: ^backend/

-   repo: https://github.com/pycqa/isort/
    rev: 5.11.4
    hooks:
    -   id: isort
        files: ^backend/

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        files: ^backend/
        additional_dependencies:
            - flake8-bugbear
            - flake8-comprehensions
            - flake8-simplify

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        files: ^backend/
        additional_dependencies: [types-all]
        args: [--disallow-any-generics, --disallow-incomplete-defs, --disallow-untyped-defs, --no-implicit-optional, --warn-unused-ignores, --warn-return-any, --check-untyped-defs, --show-error-codes, --warn-unused-configs, --show-column-numbers, --ignore-missing-imports, --namespace-packages
        ]
