exclude: "^docs/|/migrations/"
default_stages: [commit, merge-commit, push]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        files: ^backend/

-   repo: https://github.com/pycqa/isort/
    rev: 5.11.4
    hooks:
    -   id: isort
        files: ^backend/
        args: ["--config=.isort.cfg"]

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: ["--config=.flake8"]
        files: ^backend/
        # additional_dependencies:
        # - flake8-absolute-import
        # - flake8-bugbear
        # - flake8-class-attributes-order
        # - flake8-comprehensions
        # - flake8-debugger
        # - flake8-django
        # - flake8-newspaper-style
        # - flake8-no-implicit-concat
        # - flake8-no-pep420
        # - flake8-print
        # - flake8-pytest-style
        # - flake8-simplify
        # - flake8-warnings

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        files: ^backend/
        args: ["--config=.mypy.ini"]
        # additional_dependencies: [types-all]
        # args: [--disallow-any-generics, --disallow-incomplete-defs, --disallow-untyped-defs, --no-implicit-optional, --warn-unused-ignores, --warn-return-any, --check-untyped-defs, --show-error-codes, --warn-unused-configs, --show-column-numbers, --ignore-missing-imports, --namespace-packages
        # ]
