default_stages: [commit, merge-commit, push]
exclude: |
    (?x)(
        ^docs/|
        /migrations/|
        ^.envs/|
        ^.coveragerc|
        ^backend/docker/
    )

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: debug-statements

    - repo: https://github.com/psf/black
      rev: 23.3.0
      hooks:
          - id: black
            files: ^backend/

    - repo: https://github.com/pycqa/isort/
      rev: 5.12.0
      hooks:
          - id: isort
            files: ^backend/
            args: ["--settings-path=backend/.isort.cfg"]

    - repo: https://github.com/PyCQA/flake8
      rev: 6.0.0
      hooks:
          - id: flake8
            files: ^backend/
            args: ["--config=backend/setup.cfg"]
            additional_dependencies:
                - flake8-absolute-import
                - flake8-bugbear
                - flake8-class-attributes-order
                - flake8-comprehensions
                - flake8-debugger
                - flake8-django
                - flake8-newspaper-style
                - flake8-no-implicit-concat
                - flake8-no-pep420
                - flake8-print
                - flake8-pytest-style
                - flake8-simplify
                - flake8-warnings

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v3.0.0-alpha.6"
      hooks:
          - id: prettier
            files: ^frontend/
            additional_dependencies:
                - "@trivago/prettier-plugin-sort-imports"
                - prettier-plugin-tailwindcss
                - prettier-linter-helpers

dev_ci:
    autoupdate_schedule: weekly
    skip: []
    submodules: false
