version: '3.9'

volumes:
  postgres_data:

services:

  web:
    container_name: local_django
    # restart: always
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./backend:/src:z
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/docker.env
      - ./.envs/postgres.env
    # environment:
    # - SECRET_KEY=${SECRET_KEY}
    # - DEBUG=${DEBUG}
    # - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db
    command: /django.sh
  db:
    image: postgres:15-alpine
    container_name: local_postgres
    env_file:
      - ./.envs/postgres.env
    # environment:
    #   - POSTGRES_HOST=${POSTGRES_HOST}
    #   - POSTGRES_PORT=${POSTGRES_PORT}
    #   - POSTGRES_DB=${POSTGRES_DB}
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
    - "5432:5432/tcp"
    - "5433:5432"