version: "3.9"

services:

  tests:
    container_name: tests_django
    platform: linux/amd64
    env_file:
      - ./.envs/postgres.env
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    command: /dev_valid.sh
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: local_postgres
    env_file:
      - ./.envs/postgres.env
