version: "3.9"

volumes:
  postgres_data:

services:

  web:
    container_name: local_django
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./backend:/src:z
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/docker.env
      - ./.envs/postgres.env
    depends_on:
      - db
    command: /django.sh
  db:
    image: postgres:15-alpine
    container_name: local_postgres
    restart: always
    env_file:
      - ./.envs/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
    - "5432:5432/tcp"
    - "5433:5432" # second port to connect to dbeaver
