version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: local_postgres
    env_file:
      - ./.envs/postgres.env
    ports:
    - "5432:5432"
    
  web:
    container_name: local_django
    build: 
      context: ./backend
      dockerfile: .docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/src:z
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db