# Generated by Django 4.1.6 on 2023-02-04 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(null=True, verbose_name="date of birth"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="salary",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=0, message="Salary cannot be less than 0"
                    )
                ],
                verbose_name="brutto salary",
            ),
        ),
    ]
