# Generated by Django 4.1.6 on 2023-02-15 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2007, 2, 19, 16, 59, 30, 539366, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Birth date",
            ),
        ),
    ]
