# Generated by Django 4.1.6 on 2023-02-15 21:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_alter_profile_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="financials",
            name="have_extra_salary",
            field=models.BooleanField(
                default=True, verbose_name="Have you extra salary for over time?"
            ),
        ),
        migrations.AlterField(
            model_name="financials",
            name="contract",
            field=models.CharField(
                choices=[
                    ("employment", "Employment contract"),
                    ("commission", "Commission contract"),
                    ("specific-task", "Specific-task contract"),
                    (
                        "commission with economic entity",
                        "Commission contract with an economic entity",
                    ),
                    ("intership", "Student and postgraduate internship contract"),
                ],
                default="employment",
                max_length=50,
                verbose_name="Type of contract",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2007, 2, 19, 21, 16, 49, 866412, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Birth date",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
