# Generated by Django 4.1.6 on 2023-02-08 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_profile_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="extra_hours_brutto_salary",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=0, message="Salary cannot be less than 0"
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=9999999999,
                        message="Sorry, but we need to have some limits",
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="hours_brutto_salary",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=0, message="Salary cannot be less than 0"
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=9999999999,
                        message="Sorry, but we need to have some limits",
                    ),
                ],
            ),
        ),
    ]
