# Generated by Django 4.1.6 on 2023-02-13 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_profile_extra_hours_brutto_salary_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="extra_hours_brutto_salary",
            new_name="extra_hourly_pay",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="hours_brutto_salary",
            new_name="hourly_pay",
        ),
    ]
