# Generated by Django 4.1.6 on 2023-02-15 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_profile_birth_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="financials",
            old_name="student",
            new_name="is_student",
        ),
        migrations.AlterField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Birth date"
            ),
        ),
    ]
