# Generated by Django 4.1.7 on 2023-02-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presentation_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presentationmodel",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
