# Generated by Django 4.1.7 on 2023-02-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presentation_app", "0002_alter_presentationmodel_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presentationmodel",
            name="title",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
