# Generated by Django 4.1.7 on 2023-02-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presentation_app", "0003_alter_presentationmodel_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presentationmodel",
            name="title",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
