# Generated by Django 4.1.5 on 2023-01-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="end_job",
            field=models.DateTimeField(blank=True, verbose_name="Stop working"),
        ),
    ]
