# Generated by Django 4.1.6 on 2023-02-15 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="from_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Event author",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="to_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Event performer",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
