# Generated by Django 4.1.5 on 2023-01-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_alter_job_end_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="end_job",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Stop working"
            ),
        ),
    ]
