# Generated by Django 4.1.5 on 2023-01-30 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0003_alter_job_end_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
