# Generated by Django 4.1.6 on 2023-02-23 20:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schedules", "0005_category_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="categories",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
