name: frontend-example

env:
    DOCKER_BUILDKIT: 1
    COMPOSE_DOCKER_CLI_BUILD: 1

on:
    pull_request:
        branches:
            - main
            - develop
            - master
            - 50-github-actions-tests

    push:
        branches:
            - main
            - develop
            - master
            - 50-github-actions-tests
jobs:
    vite:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code Repository
              uses: actions/checkout@v3
            - name: Build the Stack
              run: docker-compose build

    cypress-e2e:
        runs-on: ubuntu-latest
        container:
            image: cypress/browsers
            options: --user 1001
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Cypress run
              uses: cypress-io/github-action@v5
              with:
                  browser: chrome
                  build: docker-compose run --rm frontend npm run build
                  start: docker-compose run --rm frontend npm run dev
                  working-directory: frontend

    vitest-tests:
        runs-on: ubuntu-latest
        needs: vite
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Vitest
              run: docker-compose run frontend sh -c 'npm run vite'
            - name: Vitest Coverage
              run: docker-compose run frontend sh -c 'npm run coverage'
            - name: Prettier
              run: docker-compose run frontend sh -c 'npm run prettier'
            - name: Lint
              run: docker-compose run frontend sh -c 'npm run lint'
            - name: Lint-fix
              run: docker-compose run frontend sh -c 'npm run lint:fix'

