name: CI

env:
    DOCKER_BUILDKIT: 1
    COMPOSE_DOCKER_CLI_BUILD: 1

on:
    pull_request:
        branches: ["main", "develop"]

    push:
        branches: ["main", "develop"]

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code Repository
              uses: actions/checkout@v3
            - name: Build the Stack
              run: docker-compose build

    vite:
        runs-on: ubuntu-latest
        needs: docker
        steps:
            - name: Run frontend
              run: docker-compose run --rm frontend

    cypress-run:
        runs-on: ubuntu-latest
        container:
            image: cypress/browsers
            options: --user 1001
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Cypress run
              uses: cypress-io/github-action@v5
              with:
                  browser: chrome
                  working-directory: frontend

    vitest-coverage-run:
        runs-on: ubuntu-latest
        needs: django
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Vitest Run
              run: docker-compose run frontend sh -c 'npm run coverage'

