name: frontend-example

env:
    DOCKER_BUILDKIT: 1
    COMPOSE_DOCKER_CLI_BUILD: 1

on:
    pull_request:
        branches:
            - main
            - develop
            - master
            - 50-github-actions-tests

    push:
        branches:
            - main
            - develop
            - master
            - 50-github-actions-tests
jobs:
    vite:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code Repository
              uses: actions/checkout@v3
            - name: Build the Stack
              run: docker-compose build
            - name: Tear down the Stack
              run:  docker-compose down

    cypress-e2e:
        runs-on: ubuntu-latest
        container:
            image: cypress/browsers
            options: --user 1001
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Cypress run
              uses: cypress-io/github-action@v5
              with:
                  browser: chrome
                  build: npm run build
                  start: npm run dev
                  working-directory: frontend

    vitest-tests:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./frontend
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Vitest install
              run: npm i
            - name: Vitest build
              run: npm run build
            - name: Prettier
              run: npm run prettier
            - name: Lint
              run: npm run lint
            - name: Lint-fix
              run: npm run lint:fix
            - name: Vitest Coverage
              run: npm run coverage
            - name: Report Coverage
              uses: davelosert/vitest-coverage-report-action@v1


